Celem zadania była implementacja algorytmu min-max, bez obcinania alfa-beta.

In [ ]:
import numpy as np
from sys import maxsize
#author Michał Iskra

In [ ]:
class Nodes: #class which contains tree of game states starting from actual and having depth levels
  def __init__(self, np_board, player, depth, heuristic_func):
    self.board = np_board   
    self.player = player
    self.depth = depth
    self.score = heuristic_func(self.board)
    self.children = []
    self.nodes_generator()
    

  def nodes_generator(self): #method to create all possible children nodes from actual node according to game rules
    if self.depth>=0:
      for cell in np.nditer(self.board, op_flags=['readwrite']):
        if cell[...] == 0:
          cell[...] = self.player
          childboard = self.board.copy()
          self.children.append(Nodes(childboard, -self.player, self.depth-1, heuristic_func))
          cell[...] = 0    
        
  def getBoard(self):
    return self.board
  def getChildren(self):
    return self.children 
  def getScore(self):
    return self.score 


def isWinner(board):
  for row in board:                            #checking rows and columns for winner
    if (len(set(row)) == 1) and (row[0] != 0):
      return True ,maxsize*row[0]              #returning maxsize with player sign
  for row in np.transpose(board):
    if (len(set(row)) == 1) and (row[0] != 0):
      return True, maxsize*row[0]

  if (len(set([board[i][i] for i in range(len(board))])) == 1) and (board[0][0] != 0):            #checking diagonals
      return True, maxsize*board[0][0]                                                           #returning maxsize with player sign
  if (len(set([board[i][len(board)-i-1] for i in range(len(board))])) == 1) and (board[0][0] != 0): 
      return True, maxsize*board[0][len(board)-1]     

  return False, 0
  

def heuristic_func(board): #function to evaluate score of board state
  winner, value = isWinner(board) #if there is winning position
  if winner:
    return value
  points = np.array([[3,2,3],[2,4,2],[3,2,3]])
  return np.sum(board*points)



def minmax(node, player, depth, heuristic_func):


  if (node.depth == 0) or (abs(node.getScore())==maxsize): #when it reaches the limit of depth or there occurs final state of game it returns board and the score of the board

    return node.getBoard().copy(), node.getScore().copy()

  board_out = np.array([[0,0,0],[0,0,0],[0,0,0]])  #mutable just for assign purpose

  if node.player == -1: #we are estimating best score for player -1
    best_score = maxsize #the maximum
    for child in node.getChildren():
      if child.getScore() <= best_score: #for player -1 we are looking for minimum value
        best_board, best_score =  minmax(child, -player, depth-1, heuristic_func)
        board_out = child.getBoard()
  else:
    best_score = -maxsize #the minimum
    for child in node.getChildren():
      if child.getScore() >= best_score: #for player 1 we are looking for maximum value
        best_board, best_score =  minmax(child, -player, depth-1, heuristic_func)
        board_out = child.getBoard()
  
  return board_out, best_score #it returns the best board scenario for player, and the evaluated best score in depth moves according to minmax algorithm
    
  
  
actualboard = np.array([[1,0,1],[0,-1,0],[0,0,0]]) #creating tic tac toe board, where -1 is player1, 1 is player2, 0 is empty space
print("INPUT board:\n{}".format(actualboard))
tree = Nodes(actualboard,-1,3,heuristic_func)
board, score = minmax(tree, -1, 3, heuristic_func)
print("OUTPUT board:\n{}".format(board))

print("\n\n")

actualboard = np.array([[1,0,-1],[0,-1,0],[1,0,0]]) #creating tic tac toe board, where -1 is player1, 1 is player2, 0 is empty space
print("INPUT board:\n{}".format(actualboard))
tree = Nodes(actualboard,-1,4,heuristic_func)
board, score = minmax(tree, -1, 4, heuristic_func)
print("OUTPUT board:\n{}".format(board))

INPUT board:
[[ 1  0  1]
 [ 0 -1  0]
 [ 0  0  0]]
OUTPUT board:
[[ 1 -1  1]
 [ 0 -1  0]
 [ 0  0  0]]



INPUT board:
[[ 1  0 -1]
 [ 0 -1  0]
 [ 1  0  0]]
OUTPUT board:
[[ 1  0 -1]
 [-1 -1  0]
 [ 1  0  0]]
